require("user.indent-blankline")
--[[ require("user.todo-highlight") ]]
require("user.smart-splits")
require("user.toggle-term")
require("user.bufferline")
require("user.illuminate")
require("user.fold-cycle")
require("user.treesitter")
require("user.rust-tools")
require("user.git-signs")
require("user.neo-tree")
require("user.stablize")
require("user.autosave")
require("user.dressing")
--[[ require("user.lsp-kind") ]]
require("user.comment")
require("user.lualine")
require("user.options")
require("user.plugins")
require("user.onedark")
require("user.discord")
require("user.autocmd")
require("user.winbar")
require("user.remap")
require("user.folds")
require("user.alpha")
require("user.tint")
require("user.cmp")
require("user.lsp")

require("nvim-autopairs").setup()
require("telescope").setup()
require('colorizer').setup()
--[[ require("which-key").setup() ]]
