local set = vim.opt

set.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.wo.fillchars = 'eob: '
set.relativenumber = true
set.termguicolors = true
set.errorbells = false
vim.g.mapleader = " "
set.smartindent = true
set.cursorline = true
set.splitbelow = true
set.cmdheight = 0
set.splitright = true
set.timeoutlen = 1000
set.incsearch = true
set.swapfile = false
set.hlsearch = false
set.undofile = true
set.updatetime = 50
set.softtabstop = 4
set.shiftwidth = 4
set.backup = false
set.hidden = true
set.wrap = false
set.tabstop = 4
set.mouse = "a"
set.nu = true
